# Generated by Django 3.2.8 on 2022-02-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('password', models.CharField(max_length=30)),
                ('isStudent', models.BooleanField()),
                ('isCreator', models.BooleanField()),
                ('isApprover', models.BooleanField()),
                ('domainType', models.CharField(max_length=50)),
            ],
        ),
    ]
