# Generated by Django 3.2.8 on 2022-02-13 17:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='domainType',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=5),
        ),
    ]
