# Generated by Django 3.2.8 on 2022-03-02 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizoApp', '0003_alter_user_info_domaintype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('mobile_number', models.BigIntegerField()),
                ('isStudent', models.BooleanField()),
                ('isCreator', models.BooleanField()),
                ('isApprover', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
