# Generated by Django 3.2.8 on 2022-03-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoApp', '0006_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=20),
        ),
    ]
