# Generated by Django 3.2.8 on 2022-03-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoApp', '0008_auto_20220312_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='DifficultyLevel',
            field=models.IntegerField(default=0),
        ),
    ]
