# Generated by Django 4.0 on 2022-03-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoApp', '0014_profile_auth_token_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
