# Generated by Django 3.2.8 on 2022-03-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizoApp', '0015_profile_forgot_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Mode', models.CharField(max_length=10)),
                ('private_code', models.CharField(max_length=10)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('QuestionSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizoApp.question')),
            ],
        ),
    ]
