# Generated by Django 3.2.8 on 2022-03-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoApp', '0016_auto_20220328_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='private_code',
            field=models.CharField(default=-1, max_length=10),
        ),
    ]
