# Generated by Django 3.2.8 on 2022-03-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoApp', '0017_auto_20220328_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
