# Generated by Django 3.2.8 on 2022-03-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoApp', '0020_quiz_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
