# Generated by Django 3.2.8 on 2022-03-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoApp', '0023_remove_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ques_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
