# Generated by Django 3.2.8 on 2022-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoApp', '0025_alter_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
    ]
