# Generated by Django 3.2.8 on 2022-03-31 10:09

from django.db import migrations, models
import quizoApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizoApp', '0026_auto_20220331_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default=quizoApp.models.from_1, primary_key=True, serialize=False),
        ),
    ]
